site_name: Scientific Machine Learning (SciML)
site_author: Krishna Kumar
site_description: Course materials for Scientific Machine Learning
site_url: https://github.com/kks32-courses/ut-portugal-sciml
repo_url: https://github.com/kks32-courses/ut-portugal-sciml
use_directory_urls: false
repo_name: SciML Course Repo

theme:
  name: material
  logo: chishiki.png
  favicon: chishiki.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.indexes
    - navigation.tracking
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - announce.dismiss
  
  icon:
    repo: fontawesome/brands/github
  

plugins:
  - search
  - mkdocs-jupyter:
      execute: false
      include_source: true
      ignore_h1_titles: true
      show_input: true
      theme: light
  - git-revision-date-localized:
      type: date
  
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: "🔗"
  
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/contrib/auto-render.min.js
  - javascripts/katex.js
  - javascripts/adaptive-width.js

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.css
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Multi-Layer Perceptron: 
    - MLP: 00-mlp/mlp.ipynb
    - Activation Function ReLU: 00-mlp/relu.md
    - Automatic Differentiation: 00-mlp/ad.md
    - Gradient Descent: 00-mlp/sgd.md
  - PINNs:
    - PINNs oscillator: 01-pinn/pinn.ipynb
    - Soft vs Hard constraint: 01-pinn/poisson.ipynb
    - Inverse analysis: 01-pinn/inverse-heat.ipynb
  - DeepONet:
    - DeepONet: 02-deeponet/deeponet.ipynb
    - DeepONet Interpretation: 02-deeponet/deeponet-explanation.md
    - DeepONet Batch Einsum: 02-deeponet/einsum.md
  - DiffSim:
    - Differentiable Simulations: 03-diffsim/diffsim.ipynb
    - DiffSim Projectile: 03-diffsim/projectile.md

copyright: |
  &copy; 2025 <a href="https://github.com/kks32-courses"  target="_blank" rel="noopener">Krishna Kumar</a>